### PR TITLE
Achievement Section

### PR DESCRIPTION
**Pull request by danmolloy**
Hi Biswajeet,

Here is an achievement section. I've decided to make them flip cards, hopefully they're to your liking.

I've tried to keep the code concise, however here is a brief explanation of what I've done:
- Created dummy data in assets/achievementsList.js
- Created a new Achievement folder, with AchievementCard.jsx, Achievements.css and Achievements.jsx
- Followed fairly similar JS to experience.jsx to render the cards
- Used CSS to make them flip, following [W3 Schools](https://www.w3schools.com/howto/howto_css_flip_card.asp)

I'm not entirely pleased with the background color of the achievement cards, what you've done on other pages is more tasteful. I spent some time fiddling with it but wasn't pleased with the results! 
Apart from that however I hope you find my additions useful. I like your website!

Best, Dan

### CODE REVIEW

**Comment by bislara** [comment]
Hey @danmolloy 

First I am sorry for the delay in checking. I got caught up in something. 
I checked your page and it really looks awesome. Good job. 
There are a few bugs/changes I could like to suggest

1. The achievements page is not responsive, ie some portions of the card is being cut in mobile view. 
Below is a view of it. Please fix this. If you are not sure how to do that, you can refer to project or experience page and make it responsive using css
image

2. I would suggest to put around 3 cards in a row. It will look better I suppose. 
3. Change the background color of the card to #3e97f6

That flipping things is really cool bro. I love that.🔥🔥

One more thing. Did you use yarn for doing the work? 
I have put the npm configuration is netilify (since I used that in my local). I guess thats why the deloy-preview is getting errors. I am not sure though whether the issue is in this npm/yarn or something else. 
image

Do you have any issue in switching to npm? else we can look for some other workaround. Do let me know ✌

**Comment by danmolloy** [comment]
Hi Biswajeet,

Thanks for the feedback, yes that's all fine. I'll send over a new pull request later today.

Best, Dan

**Comment by danmolloy** [comment]
Hi Biswajeet,

I made the changes you suggested. What are your thoughts?
I think I uninstalled yarn but admittedly not sure if there may still be an issue. Let me know.

Best wishes
Dan

**Review by bislara — APPROVED** [review]
@danmolloy Well done. 🔥🔥🎉. This looks really cool and the dependency problem is sorted as well. I will update the dummy contents of the achievements page and finally merge the PR soon. Thanks for adding this awesome page.
Cheers ✌

**Review by bislara — APPROVED** [review]
All set to merge with updated data of achievements.

**Comment by bislara** [comment]
@all-contributors please add @danmolloy for code

**Comment by bislara** [comment]
@all-contributors please add @danmolloy for code

**Comment by danmolloy** [comment]
Great! Thanks Biswajeet, glad you like it. Best, Dan

**Pull request merged**
