### PR TITLE
Timeline UI for education added

### PR DESCRIPTION
**Pull request by AbhiramKrishna88**
# Description
Added timeline style to education page to improve UI style.
Made using pure HTML CSS

# Type of change
> UI change

### CODE REVIEW

**Comment by AbhiramKrishna88** [comment]
@bislara ok?

**Comment by AbhiramKrishna88** [comment]
@bislara

**Review by bislara — CHANGES_REQUESTED** [review]
Hey, sry for getting it late. 

image

could you please increase the width in mobile view and if possible little bit in desktop view as well. I guess it would look better in this and the length of the section will decrease. Rest all looks good. Good job mate. 
Soon, this is done I will approve and merge

**Comment by AbhiramKrishna88** [comment]
image
Is it ok? 
This is the maximum. Any more reduction in spacing may affect its aesthetics.
@bislara

**Comment by bislara** [comment]
Yeah, this is fine. Check for the mobile view as well.

**Comment by AbhiramKrishna88** [comment]
@bislara 
image
Don't mind the home button it will go with scroll. and i have adjusted its z-index

**Review by bislara — APPROVED** [review]
Great, this looks perfect. Thank you @AbhiramKrishna88. 
Keep doing this awesome work 🎉🚀

**Comment by bislara** [comment]
@all-contributors please add @AbhiramKrishna88 for code

**Pull request merged**
