### PR TITLE
Sidebar edits

### PR DESCRIPTION
**Pull request by gvirus21**
# Description

Changed menu item's padding from 1em to 0.7em as requested.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by bislara** [comment]
@gvirus21 Bro this again has the changes in package-lock.json. While committing just add the CSS file and don't add all. 
✔ `git add Navbar.css` 
❌ `git add .`

**Comment by gvirus21** [comment]
haha oo..sorry about that, just a minute Let me fix it.

**Comment by gvirus21** [comment]
Heyy i am getting this issue, while I add only NavBar.css.

fatal: pathspec 'NavBar.css' did not match any files.

can you help me with this?
Screenshot (116)

**Comment by bislara** [comment]
Put the correct path and filename while adding

**Pull request closed without merging**
